### ISSUE TITLE
when shows on html shape broken

### ISSUE THREAD

**Issue by UmutAlihan** [nuvipannu/ascii-heart#2]
It is a great and creative way to learn about js. Exactly what I was looking for. Thank you!

I was writing a small apologize letter to my girlfriend as a simple nodejs webserver. As soon as she request "/love" the node returns the beautfuil heart you have developed :)

But unfortunately the node sends the requests with "\n" by doing ".toString" of cli-graph module.
I tweaked it changing "\n" to "<br/> but it this time it only shows a distorted heart :) like this:

* * * * * * * * * *
* * ❤ ❤ ❤ * * * ❤ ❤ ❤ * *
* ❤ ❤ ❤ ❤ ❤ * ❤ ❤ ❤ ❤ ❤ *
* ❤ ❤ ❤ ❤ ❤ ❤ ❤ ❤ ❤ ❤ ❤ *
* * ❤ ❤ ❤ ❤ ❤ ❤ ❤ ❤ ❤ * *
* * ❤ ❤ ❤ ❤ ❤ ❤ ❤ * *
* * ❤ ❤ ❤ ❤ ❤ * *
* * ❤ ❤ ❤ * *
* * ❤ * *
* * *
* 

Anyway I sent it to my gf. 
Since I am not perfect, my heart has also imperfection ;). I hope this perspective works, wish me luck.:)

Thank you for your beautiful simple package!

**Comment by UmutAlihan** [comment]
The changes (\n -> <br/) mentioned above is in these lines below :
( in node_modules/cli-graph/lib/index.js)
```

CliGraph.prototype.toString = function () {
    var self = this
      , str = ""
      ;

    for (var i = 0; i < self.graph.length; ++i) {
        str += self.graph[i].join("") + "<br/>";
    }

    return str;
};
```

**Comment by IonicaBizau** [comment]
You can wrap it into a `<pre>` element and it will look nicely. 😅

**Comment by UmutAlihan** [comment]
Yeap, heart is more pretty now and  tweaking cli_graphs module is no more necessary, thank you

Even though the heart is still semi-distorted on mobile, it functions and serves for its purposewell

Thanks again,

**Comment by IonicaBizau** [comment]
It should look fine on mobile too. Just make sure you have a monospace font and nowrap.
